name: Android Lint

on:
  push:
     branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Decode Google Services JSON
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > app/google-services.json
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Start lint
        run: ./gradlew lint
