name: Detekt

on:
  push:
     branches: [ "main" ]
  pull_request:
     branches: [ "main" ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: echo API_KEY=\"$API_KEY\" > ./local.properties
      - name: Build the app
        run: ./gradlew assembleDebug
      - name: Start detekt
        run: ./gradlew detekt
